### ISSUE TITLE
Weird error when setting up the project locally

### ISSUE THREAD

**Issue by Migaroez** [CandidContributions/CanConCloud#16]
InvalidOperationException: No ClientId set.
Umbraco.Cloud.Identity.Cms.V9.B2CConfiguration.get_LocalDevelopmentScope()

**Comment by LottePitcher** [comment]
Thanks @Migaroez  

Step 1, I have replicated the problem 🎉  (having deleted my local bin/debug folder)

I thought (hoped) we could get away without having an `umbraco-cloud.json` file in the public repo as it does have secrets in but clearly not that simple. Am having a look...

**Comment by LottePitcher** [comment]
@Migaroez hope we've fixed the issue by removing the Umbraco.Cloud package references from the web project. Would appreciate hearing that you can now run the site locally (having merged in latest `main` into your PR)

Really hope that the two codebases don't need to diverge any more than this!

**Comment by Migaroez** [comment]
It is starting up now, but the username/password combination in the readme does not seem to work :(

**Comment by LottePitcher** [comment]
Closing issue as we have now confirmed the username/password does work!
